### PR TITLE
Switch to GAP 4.11.0 point release

### LINKED ISSUE #306: use shallow clone and `get(ENV, "GAP_INSTALL_PACKAGES", "no")`
when building GAP, just that we don't end up downloading the full git tree and 2.6GB of pkgs
```
~/.julia/packages/GAP/W20PN/gap/pkg on  stable-4.11 ⌚ 17:58:29
$ du -h --max-depth=1 ./ | sort -h -r
2.6G    ./
661M    ./NormalizInterface-1.1.0
465M    ./semigroups-3.2.1
247M    ./simpcomp
111M    ./CaratInterface
90M     ./transgrp
80M     ./SmallGrp-1.4.1
74M     ./sglppow-2.1
73M     ./irredsol-1.4
53M     ./tomlib-1.2.9
51M     ./YangBaxter-0.9.0
49M     ./hap-1.24
49M     ./ctbllib
48M     ./rcwa-4.6.4
47M     ./ferret-1.0.2
41M     ./primgrp-3.4.0
40M     ./PolymakeInterface-2019.09.02
40M     ./difsets-2.3.1
29M     ./kbmag-1.5.9
26M     ./digraphs-1.0.3
24M     ./smallsemi-0.6.12
19M     ./unitlib-4.0.0
18M     ./sonata-2.9.1
17M     ./FactInt-1.6.3
14M     ./anupq-3.2.1
13M     ./guava-3.15
13M     ./fining
12M     ./profiling-2.2.1
12M     ./corelg-1.53
```
also #285 would be greatly appreciated

### LINKED ISSUE #316: Some GAP docstrings are missing?
```julia
help?> GAP.Globals.ListPerm
Automata (not loaded):
  2.5-7 ListPermutedAutomata
  
  ‣ ListPermutedAutomata( aut ) ────────────────────────────────────────────────── function
  
  Given an automaton aut, returns a list of automata with permuted states
  
  ───────────────────────────────────────  Example  ───────────────────────────────────────
    gap> x:=Automaton("det",3,2,[ [ 0, 2, 3 ], [ 1, 2, 3 ] ],[ 1 ],[ 2, 3 ]);;
    gap> ListPermutedAutomata(x);
    [ < deterministic automaton on 2 letters with 3 states >, 
      < deterministic automaton on 2 letters with 3 states >, 
      < deterministic automaton on 2 letters with 3 states >, 
      < deterministic automaton on 2 letters with 3 states >, 
      < deterministic automaton on 2 letters with 3 states >, 
      < deterministic automaton on 2 letters with 3 states > ]
  ─────────────────────────────────────────────────────────────────────────────────────────
  

─────────────────────────────────────────────────────────────────────────────────────────────
```
misses the `Reference` docstring;

on the other hand
```julia
help?> GAP.Globals.PermList
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 2nd choice method found for `+' on 2 arguments
ERROR: Error thrown by GAP
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] error_handler() at /home/kalmar/.julia/dev/GAP/src/GAP.jl:48
 [3] #call_gap_func#5(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(GAP.call_gap_func), ::Main.ForeignGAP.MPtr, ::Main.ForeignGAP.MPtr, ::Vararg{Any,N} where N) at /home/kalmar/.julia/dev/GAP/src/ccalls.jl:149
 [4] call_gap_func(::Main.ForeignGAP.MPtr, ::Main.ForeignGAP.MPtr, ::Vararg{Any,N} where N) at /home/kalmar/.julia/dev/GAP/src/ccalls.jl:139
 [5] #_#5(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Main.ForeignGAP.MPtr, ::Main.ForeignGAP.MPtr, ::Vararg{Any,N} where N) at /home/kalmar/.julia/dev/GAP/src/GAP.jl:124
 [6] (::Main.ForeignGAP.MPtr)(::Main.ForeignGAP.MPtr, ::Vararg{Any,N} where N) at /home/kalmar/.julia/dev/GAP/src/GAP.jl:124
 [7] GAP_help_string(::String, ::Bool) at /home/kalmar/.julia/dev/GAP/src/help.jl:4 (repeats 2 times)
 [8] doc(::GAP.GAPHelpType, ::Type) at /home/kalmar/.julia/dev/GAP/src/help.jl:21 (repeats 2 times)
 [9] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/REPL/src/docview.jl:355
```

(I have to admit GAP docstrings are pretty cool ;-)

### LINKED ISSUE #351: Switch to using GAP 4.11.0
GAP 4.11.0 has been "almost" released: tarball is up at https://www.gap-system.org/pub/gap/gap-4.11/tar.bz2/gap-4.11.0.tar.bz2 but the website has not yet been updated.

However, that's a 400 MB tarball; so perhaps instead, we should use https://www.gap-system.org/pub/gap/gap4core/gap-4.11.0-core.zip (which is just 18 MB) plus a minimal set of packages (see also https://github.com/gap-system/gap/issues/3913)

### PR DESCRIPTION
**Pull request by fingolfin**
This actually renders a few other PRs superfluous.

Resolves #306
Resolves #316
Closes #321
Resolves #351
Closes #361

### CODE REVIEW

File: deps/build.jl [hunk 1]
```diff
@@ -22,45 +24,37 @@ julia_binary = get(ENV, "JULIA_BINARY", Sys.BINDIR)
...
 if install_gap
     println("Installing GAP ...")
-    gap_branch = "stable-4.11"
     cd(extra_gap_root)
-    run(`rm -rf gap`)
-    run(`git clone --depth=1 -b $(gap_branch) https://github.com/gap-system/gap`)
-    cd("gap")
-    run(`./autogen.sh`)
+    run(`rm -rf gap-$(gap_version)`)
+    filename = download("https://www.gap-system.org/pub/gap/gap-4.11/tar.bz2/gap-$(gap_version).tar.bz2")
```
Comment (ThomasBreuer) [inline deps/build.jl]: Can we avoid the hard-coded 4.11 in this line (and in etc/travis_install_gap.sh)?
