### PR TITLE
fix GAP help access for Julia nightly

### LINKED ISSUE #978: CI tests fail in Julia nightly: `terminal` not defined in `REPL.TerminalMenus`
This is the error:
```
help: Error During Test at /home/runner/work/GAP.jl/GAP.jl/test/help.jl:1
  Got exception outside of a @test
  UndefVarError: `terminal` not defined in `REPL.TerminalMenus`
  Suggestion: check for spelling errors or missing imports.
  Stacktrace:
    [1] getproperty(x::Module, f::Symbol)
      @ Base ./Base.jl:42
    [2] top-level scope
      @ ~/work/GAP.jl/GAP.jl/test/help.jl:2
    [3] macro expansion
      @ /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.12/Test/src/Test.jl:164 [inlined]
    [4] macro expansion
      @ ~/work/GAP.jl/GAP.jl/test/help.jl:3 [inlined]
    [5] include(fname::String)
      @ Main ./sysimg.jl:38
    [6] top-level scope
      @ ~/work/GAP.jl/GAP.jl/test/runtests.jl:14
```

@ThomasBreuer maybe you can have a look?

### PR DESCRIPTION
**Pull request by ThomasBreuer**
In Julia 1.12, one can use `default_terminal()`
instead of `REPL.TerminalMenus.terminal`.

resolves #978

### CODE REVIEW

File: src/help.jl [hunk 1]
```diff
@@ -3,8 +3,17 @@
...
+else
+  # before Julia 1.12
+  function default_terminal()
+    return REPL.TerminalMenus.terminal
+  end
+end
+
 function gap_help_string(topic::String, onlyexact::Bool = false,
-    term::REPL.Terminals.TTYTerminal = REPL.TerminalMenus.terminal;
+    term::REPL.Terminals.TTYTerminal = default_terminal();
```
Comment (fingolfin) [inline src/help.jl:16]:
```suggestion
    term::REPL.Terminals.TTYTerminal = default_terminal()
```
As far as I can tell, `term` is only used in one spot, in the call to `REPL.TerminalMenus.request` below. So perhaps we should just replace `term` there by `default_terminal();`

File: src/help.jl [hunk 2]
```diff
@@ -3,8 +3,17 @@
 import Markdown
 import REPL
 
+if isdefined( REPL.TerminalMenus, :default_terminal)
+  default_terminal = REPL.TerminalMenus.default_terminal
```
Comment (fingolfin) [inline src/help.jl:7]: Can we also do this? (Might have to use `@static if ...` above)
```suggestion
  import REPL.TerminalMenus: default_terminal
```

**Review by fingolfin — APPROVED** [review]

File: src/help.jl (hunk 1 above)
Comment (ThomasBreuer) [reply src/help.jl:16]: Here `term` is an argument for the function `gap_help_string`.
The idea behind the complicated syntax is to make this function testable, by providing input from a terminal, see `test/help.jl`.
(I think the fact that we found the problem with Julia nightly shows that this test is useful.)

Comment (fingolfin) [reply src/help.jl:16]: Ahhhhh of course you are 100% right; I completely misread the code and missed that term is an argument

File: src/help.jl (hunk 2 above)
Comment (ThomasBreuer) [reply src/help.jl:7]: Yes, this works.

File: src/help.jl [hunk 3]
```diff
@@ -3,8 +3,18 @@
 import Markdown
 import REPL
 
+if isdefined( REPL.TerminalMenus, :default_terminal)
+  import REPL.TerminalMenus: default_terminal
+# default_terminal = REPL.TerminalMenus.default_terminal
```
Comment (fingolfin) [inline src/help.jl:8]: Can this go?
```suggestion
```

File: src/help.jl [hunk 4]
```diff
@@ -3,8 +3,18 @@
 import Markdown
 import REPL
 
+if isdefined( REPL.TerminalMenus, :default_terminal)
```
Comment (fingolfin) [inline src/help.jl:6]:
```suggestion
if isdefined(REPL.TerminalMenus, :default_terminal)
```

File: src/help.jl (hunk 3 above)
Comment (ThomasBreuer) [reply src/help.jl:8]: Yes.

File: src/help.jl (hunk 4 above)
Comment (ThomasBreuer) [reply src/help.jl:6]: Yes.

**Review by fingolfin — APPROVED** [review]
